export const theme = {
  fonts: {
    body: "Gowun Dodum",
    display: "Jua",
    mono: "Menlo",
  },
  colors: {
    appBackground: "#fbfbfa",
    surface: "#ffffff",
    surfaceMuted: "#f4f4f2",
    surfaceSoft: "#f8f8f6",
    ink: "#111111",
    inkSoft: "#545454",
    muted: "#868686",
    border: "#e9e9e7",
    accent: "#111111",
    accentSoft: "#ececec",
    success: "#c9c9c9",
    shadow: "rgba(0, 0, 0, 0.05)",
  },
  radius: {
    xl: 30,
    lg: 24,
    md: 18,
    sm: 14,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
  },
  status: {
    LOW_ENERGY: {
      label: "차분",
      bubble: "오늘은 천천히.",
      description: "오늘은 조용하고 흔들리지 않는 날이에요.",
      background: ["#fbfbfa", "#f7f7f5"],
      stage: "#f3f3f1",
      bubbleSurface: "#f5f5f3",
      effect: "cloudy",
      animationSpeed: 0.72,
      bobAmount: 0.026,
    },
    NORMAL_ENERGY: {
      label: "평온",
      bubble: "도마에 맞춰 걷고 있어.",
      description: "오늘 상태는 안정적이고, 일반적으로 걸을 수 있는 분위기예요.",
      background: ["#f9f9f8", "#f1f1ef"],
      stage: "#f4f4f2",
      bubbleSurface: "#f6f6f4",
      effect: "float",
      animationSpeed: 0.98,
      bobAmount: 0.044,
    },
    HIGH_ENERGY: {
      label: "활발",
      bubble: "왜찍 더 걸어보고 싶어!",
      description: "오늘 에너지가 높아서 발걸음과 분위기가 더 살아내요.",
      background: ["#fafafa", "#f3f3f1"],
      stage: "#f4f4f2",
      bubbleSurface: "#f5f5f3",
      effect: "sparkle",
      animationSpeed: 1.18,
      bobAmount: 0.06,
    },
  },
  growth: {
    WEAK: {
      label: "성장 초기",
      bubble: "아직 기본이 만들어지는 중이에요.",
      description: "누적 걸음이 아직 적어서 기본 형상이 천천히 자리을 맡아가는 상태예요.",
    },
    HEALTHY: {
      label: "건강",
      bubble: "서둘이 매일 맞아져가고 있어.",
      description: "걸음이 커질 수록 모습이 안정적이고 단단해지는 상태예요.",
    },
    ACTIVE: {
      label: "활동적",
      bubble: "원동이 강하게 있어!",
      description: "오랜 시간 걸음이 쌓이는 만큼 더 두탈하고 활발한 상태예요.",
    },
  },
};

