export const STAGE_MODE = "character-only";

export const SKIN_TONE_PRESETS = [
  { id: "fair-1", label: "\uD1A4 1", color: "#f7d9cf" },
  { id: "fair-2", label: "\uD1A4 2", color: "#f4cbbb" },
  { id: "fair-3", label: "\uD1A4 3", color: "#efbda8" },
  { id: "fair-4", label: "\uD1A4 4", color: "#efb08f" },
  { id: "deep-1", label: "\uD1A4 5", color: "#f29d6d" },
  { id: "deep-2", label: "\uD1A4 6", color: "#d77c54" },
  { id: "deep-3", label: "\uD1A4 7", color: "#af6547" },
  { id: "deep-4", label: "\uD1A4 8", color: "#8d5543" },
];

export const CHARACTER_CLASSES = [
  {
    id: "custom-chibi",
    label: "\uB0B4 \uCE90\uB9AD\uD130",
    blurb: "\uC0B0\uCC45\uC5D0 \uB530\uB77C \uC870\uAE08\uC529 \uC560\uCC29\uC774 \uC313\uC774\uB294 \uB0B4 SD \uCE90\uB9AD\uD130",
    modelSignature: ["custom-glb", "blender-import"],
    modelUrl: "models/chibi_animated.glb",
    modelScale: [2.72, 2.72, 2.72],
    modelOffset: [0, 1.74, 0],
    modelPivotY: 0.62,
    modelRotation: [0, 0, 0],
    animationMap: {
      idle: "neutralIdle",
      tired: "sittingIdle",
      sleepyIdle: "breathingIdle",
      idleBreathing: "breathingIdle",
      relaxedIdle: "neutralIdle",
      lookAround: "lookAround",
      lookingDown: "lookingDown",
      weightShift: "weightShift",
      yawn: "yawn",
      idleTransition: "idleTransition",
      standingUp: "standingUp",
      startWalking: "startWalking",
      stopWalking: "stopWalking",
      runToStop: "runToStop",
      slowWalk: "walking",
      walk: "walking",
      fastWalk: "walking",
      casualWalk: "walking",
      exploreWalk: "walking",
      energeticWalk: "walking",
      activePatrol: "walking",
      lightJog: "slowRun",
      run: "running",
      happyRun: "running",
    },
    animationSources: {
      neutralIdle: "models/animations/neutral-idle.fbx",
      breathingIdle: "models/animations/breathing-idle.fbx",
      sittingIdle: "models/animations/sitting-idle.fbx",
      lookAround: "models/animations/look-around.fbx",
      lookingDown: "models/animations/looking-down.fbx",
      weightShift: "models/animations/weight-shift.fbx",
      yawn: "models/animations/yawn.fbx",
      idleTransition: "models/animations/idle-transition.fbx",
      standingUp: "models/animations/standing-up.fbx",
      startWalking: "models/animations/start-walking.fbx",
      stopWalking: "models/animations/stop-walking.fbx",
      runToStop: "models/animations/run-to-stop.fbx",
      walking: "models/animations/walking.fbx",
      slowRun: "models/animations/slow-run.fbx",
      running: "models/animations/running.fbx",
    },
    defaultAnimation: "idle",
    palette: {
      primary: "#f3f4f6",
      secondary: "#ffffff",
      accent: "#585d66",
      hair: "#6b4a37",
      skin: "#f7d9cf",
      detail: "#1f232b",
      hat: "#d5d8de",
      trim: "#8d939c",
    },
  },
];
